name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-linux:
    runs-on: ubuntu-20.04
    env:
      CC: gcc
    steps:
      - name: Install V
        id: install-v
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true
      - name: Checkout v-tree-sitter
        uses: actions/checkout@v3
        with:
          path: v-tree-sitter
      - name: Run tests
        run: |
          cd v-tree-sitter
          v test .

  test-macos:
    runs-on: macos-latest
    env:
      CC: clang
    steps:
      - name: Install V
        id: install-v
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true
      - name: Checkout v-tree-sitter
        uses: actions/checkout@v3
        with:
          path: v-tree-sitter
      - name: Compile
        run: |
          cd v-tree-sitter
          v test .

  test-windows:
    runs-on: windows-latest
    env:
      CC: msvc
    steps:
      - uses: msys2/setup-msys2@v2
      - name: Install V
        id: install-v
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true
      - name: Checkout v-tree-sitter
        uses: actions/checkout@v3
        with:
          path: v-tree-sitter
      - name: Compile
        run: |
          cd v-tree-sitter
          v test .
